# x-archived-from: xpansiv-optimal-system-openapi.yml
# x-archived-on: 2026-09-16
openapi: 3.0.1
info:
  title: System API
  description: Use API credentials to check system health.
  version: 1.0.0
servers:
  - url: https://optimalapi-ext.apx.com
    description: Generated server url
  - url: https://optimalapi-uat-ext.apx.com
security:
  - JWT: []
tags:
  - name: system-v1
    description: Check the API system health.
paths:
  /optimal/v1/system/ping:
    get:
      tags:
        - system-v1
      summary: Check API server health
      description: >-
        Ping API, to ensure the API is available and your API credentials are
        valid.
      operationId: ping
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
components:
  schemas:
    Pong:
      required:
        - pong
      type: object
      properties:
        pong:
          type: string
          description: The current time on the server
          format: date-time
      description: Response indicating server health
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
